### PR TITLE
Add support for AES successAction

### LINKED ISSUE #82: Add support for LUD-10: `aes` successAction in LNURL-pay
See https://github.com/lnurl/luds/blob/luds/10.md

### PR DESCRIPTION
**Pull request by ok300**
Fixes #82

Unlike other success actions, which can be fully used as soon as we get them, this one can only be decrypted once the LNURL-pay invoice is paid. The preimage is the decryption key.

### CODE REVIEW

**Comment by ok300** [comment]
@erdemyerebasmaz  do you have access to 

https://github.com/breez/breez-sdk/blob/44e3165346b1e00be1c1d8dbf53eab6dc6464bad/libs/sdk-core/src/lnurl/pay.rs#L225

in Dart, in order to decrypt the payload when needed? Or should I expose it via some other way?

**Comment by erdemyerebasmaz** [comment]
> @erdemyerebasmaz do you have access to
> 
> https://github.com/breez/breez-sdk/blob/44e3165346b1e00be1c1d8dbf53eab6dc6464bad/libs/sdk-core/src/lnurl/pay.rs#L225
> 
> in Dart, in order to decrypt the payload when needed? Or should I expose it via some other way?

No I'm afraid but this is a good opportunity to test this feature of flutter_rust_bridge: https://cjycode.com/flutter_rust_bridge/feature/lang_methods.html

**Comment by roeierez** [comment]
> No I'm afraid but this is a good opportunity to test this feature of flutter_rust_bridge: https://cjycode.com/flutter_rust_bridge/feature/lang_methods.html

This is indeed a nice feature but let's be carfull as we need to support that in uniffi as well and the support is  different there where there is a differentiation between data structs and interfaces.

**Comment by roeierez** [comment]
> in Dart, in order to decrypt the payload when needed? Or should I expose it via some other way?

@ok300  Why not decrypt the payload in rust after the payment and put the decrypted value in the success action?

**Comment by roeierez** [comment]
> @ok300 Why not decrypt the payload in rust after the payment and put the decrypted value in the success action?

@ok300 did you consider this suggestion?

**Comment by ok300** [comment]
Yes, that's what I'm looking into.

I originally wanted to persist the decrypted payload, but its maybe simpler to try to decrypt on the fly.

**Comment by ok300** [comment]
@roeierez looks like even the simplest version was more complicated than I thought :)

Created as a separate PR on top of this one: #88

**Review by roeierez — APPROVED** [review]

**Pull request merged**
