### PR TITLE
Update bindings-kotlin-multiplatform to use version catalog

### PR DESCRIPTION
**Pull request by angelix**
Update dependencies
```
atomicfu = "0.24.0"
android-gradle-plugin = "8.4.1"
jna = "5.14.0"
kotlin = "1.9.24"
kotlinx-datetime = "0.6.0"
okio = "3.9.0"
```

### CODE REVIEW

**Review by roeierez — APPROVED** [review]
LGTM

**Comment by roeierez** [comment]
@dangeross can you review this please?

**Review by dangeross — APPROVED** [review]
LGTM, it also brings the JNI version inline with the android bindings. 

@angelix were you able to test locally, or shall we create a pre-release build so you can test?

**Comment by angelix** [comment]
> LGTM, it also brings the JNI version inline with the android bindings.
> 
> @angelix were you able to test locally, or shall we create a pre-release build so you can test?

@dangeross haven't test it, a pre-release would be great.

**Pull request merged**
