### PR TITLE
Add freezed annotation on SDK structs used through Dart bindings

### PR DESCRIPTION
**Pull request by erdemyerebasmaz**
- All SDK structs exposed through Dart bindings that reference another SDK struct has to be annotated. Including the referenced struct.

- Not needed on structs that only has supported types so enums are excluded. https://cjycode.com/flutter_rust_bridge/v1/feature/lang_simple.html

### CODE REVIEW

**Comment by dangeross** [comment]
@erdemyerebasmaz with v2 of the flutter_rust_bridge do we still need to do this?

**Comment by erdemyerebasmaz** [comment]
> flutter_rust_bridge

@dangeross I'm not exactly sure if v2 changes would also generate `toString` methods without these annotations.
> - Use arbitrary Rust and Dart types without manual intervention, even if they are not serializable or non-clone.
>  - Generate hashCode/equals for non-freezed structs.

 I'll setup an example project using v2 to find out.

**Comment by roeierez** [comment]
@erdemyerebasmaz it seems that v2 also supports structure errors so we should consider seriously to upgrade.

**Comment by erdemyerebasmaz** [comment]
> @erdemyerebasmaz it seems that v2 also supports structure errors so we should consider seriously to upgrade.

I didn't want to upgrade yet as it's in beta and we were getting ready for releasing c-breez. I'll look into it.

Should we merge this as there's an open PR on C-Breez that depends on this?

**Comment by erdemyerebasmaz** [comment]
Superseded by #940

**Pull request closed without merging**
