### PR TITLE
Add Error rustdocs descriptions

### LINKED ISSUE #837: Improve error descriptions in rustdocs
Add an error description and optional example for each error variant.

https://breez.github.io/breez-sdk/breez_sdk_core/error/index.html

### PR DESCRIPTION
**Pull request by dangeross**
Add a short description of each public enum error variant.

Fixes #837

### CODE REVIEW

**Review by ok300 — COMMENTED** [review]
Maybe it's a bit too verbose, in that the name of the error is obvious from the enum value? If so, the first 2 lines of every new rustdoc could be removed.

What do you think?

**Comment by dangeross** [comment]
> Maybe it's a bit too verbose, in that the name of the error is obvious from the enum value? If so, the first 2 lines of every new rustdoc could be removed.
> 
> What do you think?

Maybe it's a bit verbose, I added the titles because Relai were asking for the error meanings

**Comment by ok300** [comment]
From the chat, it looks like the description is what they mainly wanted.

**Comment by dangeross** [comment]
> From the chat, it looks like the description is what they mainly wanted.

Yep, I'll make the change

**Review by ok300 — APPROVED** [review]

**Pull request merged**
