### PR TITLE
Add convenience tasks to check fmt and clippy

### PR DESCRIPTION
**Pull request by dangeross**

### CODE REVIEW

**Comment by ok300** [comment]
`cargo fmt --all`  and `cargo clippy --all` will also cover tests.

**Comment by dangeross** [comment]
`cargo clippy --all` does seem to cover tests for me

**Comment by ok300** [comment]
Good catch, that should be `cargo clippy --tests`

**Comment by ok300** [comment]
You can have a look how we do it in the CI:
* https://github.com/breez/breez-sdk/blob/main/.github/workflows/main.yml#L15-L25
* https://github.com/breez/breez-sdk/blob/main/.github/workflows/main.yml#L166-L173

**Comment by dangeross** [comment]
> You can have a look how we do it in the CI:

This is exactly where I copied them from 😄 Just so I can to a quick pre-commit check

**Review by roeierez — APPROVED** [review]

**Pull request merged**
