### PR TITLE
Update uniffi-kotlin-multiplatform

### PR DESCRIPTION
**Pull request by dangeross**
Update to fix buffer not being exhausted during allocation to rust buffer

### CODE REVIEW

**Review by roeierez — APPROVED** [review]
Fantastic!

**Comment by angelix** [comment]
Excellent work @dangeross.
I want to add a test on your PR to bullet proof feature refactors.

**Comment by roeierez** [comment]
> Excellent work @dangeross. I want to add a test on your PR to bullet proof feature refactors.

@angelix thank you! should we wait for the test?

**Comment by angelix** [comment]
No, don't wait. I'll make a PR in the upstream project at some point.

**Pull request merged**
