### PR TITLE
Update pubspec flutter version

### PR DESCRIPTION
**Pull request by ademar111190**
I'm running the following version of flutter, and I got this pubspec update on my last build.

```
flutter --version                                                                                                                                                                                                                                                               ─╯
Flutter 3.7.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b06b8b2710 (4 weeks ago) • 2023-01-23 16:55:55 -0800
Engine • revision b24591ed32
Tools • Dart 2.19.0 • DevTools 2.20.1
```

### CODE REVIEW

**Comment by erdemyerebasmaz** [comment]
@roeierez Can we remove InputParser from sdk-flutter now?

**Comment by roeierez** [comment]
> @roeierez Can we remove InputParser from sdk-flutter now?

Yes

**Comment by erdemyerebasmaz** [comment]
@ademar111190 Flutter stable is at 3.7.3, please upgrade it.
It reverted that line for me upon running flutter pub get. I'm converting this issue into removal of InputParser and it's plugins.

**Comment by ademar111190** [comment]
> @ademar111190 Flutter stable is at 3.7.3, please upgrade it. It reverted that line for me upon running flutter pub get. I'm converting this PR into removal of InputParser and it's plugins.

Ohh I see, thanks 👍

**Comment by erdemyerebasmaz** [comment]
@roeierez can you review https://github.com/breez/breez-sdk/commit/92b49129807da730e59456305dc13bcec8246541?
Ademar removed the branch of this PR and I pushed it to main by mistake while trying to cherry-pick it to another branch.

**Comment by erdemyerebasmaz** [comment]
> > @roeierez Can we remove InputParser from sdk-flutter now?
> 
> Yes

We were still using InputProtocol and some parts of parser on InputHandler & InputBloc. I've reverted the changes.
There seems to be missing pieces as well. For example, we add domain information to LNURLPayParams which is missing from LnUrlPayRequestData.

**Pull request closed without merging**
