### PR TITLE
Add react native bindings for LNURL-pay

### PR DESCRIPTION
**Pull request by ok300**

### CODE REVIEW

**Review by roeierez — APPROVED** [review]

**Review by dangeross — COMMENTED** [review]
It looks like the kotlin and swift changes still need adding.

**Comment by roeierez** [comment]
> It looks like the kotlin and swift changes still need adding.

Right, I missed the fact the native logic is not implemented @ok300

**Comment by dangeross** [comment]
Hi @ok300, if you don't mind, I'm going to branch your PR and add the native updates for kotlin and swift.

**Comment by ok300** [comment]
Hi, I was about to do that right now, but please go ahead. You'll probably do it better and faster than me.

Was struggling to see how to map the enum in the right way in the new syntaxes, without having a local compiler to give feedback if its correct or not.

**Comment by ok300** [comment]
Superseded by #149

**Pull request closed without merging**
