### PR TITLE
Ensure homebrew updates its internal list of formulas before installing

### PR DESCRIPTION
**Pull request by ok300**
This PR is a different approach for for #760

### CODE REVIEW

**Comment by ok300** [comment]
I ran the CI 3 times, the correct (latest) `ktlint` was used every time.

**Review by roeierez — APPROVED** [review]
I prefer this approach

**Review by dangeross — APPROVED** [review]
Preferred, if it keeps the version across runs consistent. We can always fallback to #760

**Comment by JssDWt** [comment]
Good stuff, I tried this too, but it took more than 6 minutes to complete. It must have been a flake, since this run completed in 1m.

**Review by JssDWt — APPROVED** [review]

**Pull request merged**
