### PR TITLE
Export Android bindings dependency of Flutter package

### PR DESCRIPTION
**Pull request by erdemyerebasmaz**
- #717 cont.
 
Exports Android bindings dependency of Flutter package so it can be accessed natively on projects that use this package.

### CODE REVIEW

**Review by cnixbtc — APPROVED** [review]
ahh that makes sense good find! 🙇 

out of curiosity: when i tested running c-breez while depending on the flutter package with the android bindings pointing to gradle, i did it with the 0.2.10 version (otherwise i had build errors in c-breez which were unrelated to the gradle change). can it be that the 2.10.0 version didn't need the bindings exported and therefore was ok with the `implementation` dependency? just wondering what i missed in testing.

**Comment by erdemyerebasmaz** [comment]
> ahh that makes sense good find! 🙇
> 
> out of curiosity: when i tested running c-breez while depending on the flutter package with the android bindings pointing to gradle, i did it with the 0.2.10 version (otherwise i had build errors in c-breez which were unrelated to the gradle change). can it be that the 2.10.0 version didn't need the bindings exported and therefore was ok with the `implementation` dependency? just wondering what i missed in testing.

The build errors were probably unrelated and due to breaking changes from the SDK.
All versions starting from 0.2.10 had Kotlin binary bundled as a resource with the plugin, that's probably why you missed this and it's understandable. We'll probably manually remove them from the breez-sdk-flutter repository after publishing the Flutter package for 0.2.14 again.

**Review by roeierez — APPROVED** [review]
LGTM

**Comment by cnixbtc** [comment]
> We'll probably manually remove them from the breez-sdk-flutter repository after publishing the Flutter package for 0.2.14 again.

They should be gone already via https://github.com/breez/breez-sdk-flutter/commit/175fbec675ef483303a3b0278536a00651c41cd9

Thanks for fixing! 🙏

**Comment by erdemyerebasmaz** [comment]
> > We'll probably manually remove them from the breez-sdk-flutter repository after publishing the Flutter package for 0.2.14 again.
> 
> They should be gone already via [breez/breez-sdk-flutter@175fbec](https://github.com/breez/breez-sdk-flutter/commit/175fbec675ef483303a3b0278536a00651c41cd9)
> 
> Thanks for fixing! 🙏

Thanks, that doesn't cover all the files we wan't to remove I'm afraid, there's 4 remaining files:
```
android/src/main/kotlin/breez_sdk/breez_sdk.kt
ios/bindings-swift/Sources/BreezSDK/BreezSDK.swift
ios/bindings-swift/Sources/BreezSDK/breez_sdkFFI.h
ios/bindings-swift/Sources/BreezSDK/breez_sdkFFI.modulemap
```

**Comment by cnixbtc** [comment]
makes sense!

**Pull request merged**
