### PR TITLE
Remove log library from sdk and move logs for the app

### PR DESCRIPTION
**Pull request by ademar111190**
SDK side of logging library changes https://github.com/breez/c-breez/pull/657

### CODE REVIEW

**Comment by roeierez** [comment]
Perhaps not use any logging library in the sdk? We have API for listening to log messages where the user can listen to and has the freedom to choose her ownogging library on the application side. Exposing the log messages as a  broadcast stream sounds good to me.

**Review by ubbabeck — APPROVED** [review]
Looks good 

tACK

**Comment by ademar111190** [comment]
Good callout @roeierez I totally agree.
I moved the logs to cbreez and removed the library.

**Review by erdemyerebasmaz — APPROVED** [review]
Looks like the right direction 👍

**Review by roeierez — APPROVED** [review]
LGTM

**Pull request merged**
