### PR TITLE
Update `flutter_rust_bridge` to `v1.82.4`(latest)

### PR DESCRIPTION
**Pull request by erdemyerebasmaz**
This PR addresses https://github.com/breez/breez-sdk-flutter/issues/4 & we may not need to deal with `FfiException`'s on Flutter apps thanks to changes on [v1.82.0](https://github.com/fzyzcjy/flutter_rust_bridge/releases/tag/v1.82.0).

#### Delay for dependency update:
Running `flutter_rust_bridge_codegen` resulted in parse errors on versions above `1.80.1`:

```
ERROR] panicked at 'called `Result::unwrap()` on an `Err` value: Error("lex error")', .cargo\registry\src\index.crates.io-6f17d22bba15001f\flutter_rust_bridge_codegen-1.81.0\src\parser\source_graph.rs:359:83
```

Not having any other information made this really hard to debug. This issue turned about to be a sneaky name & import resolution issue, which became obvious after several blind solution attempts: stripping bindings.rs, changing rust-input path not to use relative path, removing all enum & log streams etc.

After noticing [parsing rust file](https://github.com/fzyzcjy/flutter_rust_bridge/blob/6f3fa295d192a3945aab6c63ab6b533dc2aef2a9/frb_codegen/src/parser/source_graph.rs#L359) panic was happening during or after `node_api.rs` on verbose logs, the underlying issue became clear as `greenlight` also has `node_api` crate. After renaming `node_api`, I was able to generate `bridge_generated.rs`, a similar issue showed between `grpc::Rate `& `fiat::Rate` and noticed `test_utils` crate was taking precedence over `breez_services`.

Rename changes got reverted and these issues finally got addressed by reordering declarations on `lib.rs` not to disturb other bindings & requiring breaking changes..

#### Changelist:
- Move `flutter_rust_bridge_codegen` config values to `pubspec.yaml` 9d7655c1e1f7961240aad39c3796c69b9c34ec8c
- Update `flutter_rust_bridge` to `1.82.4`
  - Generate bindings
  - Update `workspace.package` & `sdk-cli` version to `0.2.10`
  - Ran `cargo update`
- Prevent `cargo fmt` from changing module declaration order on `lib.rs` 2d7e9a3208213a96a1ffc6e42e59ecdee8a41e8c

#### Known issues:
-  I believe ffi 10.x requirement issue will be resolved in a matter of days, we can wait for the next hotfix version before merging.
https://github.com/fzyzcjy/flutter_rust_bridge/issues/1427
https://github.com/fzyzcjy/flutter_rust_bridge/issues/1429

### CODE REVIEW

**Comment by sagarsubedi** [comment]
Will upgrading the version to `1.82.0` fix the error for people using bdk_flutter?
bdk_flutter needs `flutter_rust_bridge: ">1.82.3 <= 1.82.4"`

**Comment by erdemyerebasmaz** [comment]
> Will upgrading the version to `1.82.0` fix the error for people using bdk_flutter? bdk_flutter needs `flutter_rust_bridge: ">1.82.3 <= 1.82.4"`

There's a typo on the PR title, we've upgraded to latest version: 1.82.4.

**Comment by sagarsubedi** [comment]
> > Will upgrading the version to `1.82.0` fix the error for people using bdk_flutter? bdk_flutter needs `flutter_rust_bridge: ">1.82.3 <= 1.82.4"`
> 
> There's a typo on the PR title, we've upgraded to latest version: 1.82.4.

I see. Thank you. I really hope this gets merged asap. I am stuck. Thanks for your work.

**Comment by erdemyerebasmaz** [comment]
> > > Will upgrading the version to `1.82.0` fix the error for people using bdk_flutter? bdk_flutter needs `flutter_rust_bridge: ">1.82.3 <= 1.82.4"`
> > 
> > 
> > There's a typo on the PR title, we've upgraded to latest version: 1.82.4.
> 
> I see. Thank you. I really hope this gets merged asap. I am stuck. Thanks for your work.

We're waiting on
- https://github.com/fzyzcjy/flutter_rust_bridge/pull/1430

to get merged as it can cause a similar dependency issue.

All in all, everything should be ready within this week, assuming `bdk_flutter` releases a new version to address that change swiftly.

**Comment by erdemyerebasmaz** [comment]
Related issues on plugin repo are locked.
- https://github.com/fzyzcjy/flutter_rust_bridge/issues/1328
- https://github.com/fzyzcjy/flutter_rust_bridge/issues/1354

I'm referencing them here to help users that face this issue due to same underlying cause.

----

After upgrading `flutter_rust_bridge` to any version above `v1.80.1`, we've encountered:
```
...ERROR] panicked at 'called `Result::unwrap()` on an `Err` value: Error("lex error")',
.cargo\registry\src\index.crates.io-6f17d22bba15001f\flutter_rust_bridge_codegen-
1.81.0\src\parser\source_graph.rs:359:83
```
which is not very informative. 

This turned out to be a name & import resolution issue on our project, which was not present in `flutter_rust_bridge` <= `v1.81.0`. Running `flutter_rust_bridge_codegen` with `--verbose` flag to show debug messages should point you to the problematic file and you can work your way from there. 

If you're facing this error for a different reason, please open an issue on [flutter_rust_bridge](https://github.com/fzyzcjy/flutter_rust_bridge/) repository.

----

**Review by roeierez — APPROVED** [review]
LGTM

**Pull request merged**
