### PR TITLE
check git status of react native and flutter

### PR DESCRIPTION
**Pull request by JssDWt**
Run the react native and flutter code generation in the main pull request CI and then run `git status` to see whether there is a diff. There shouldn't be a diff.

Also updates the used flutter version in CI. I noticed the old version was used.

### CODE REVIEW

**Comment by JssDWt** [comment]
I love it that it caught a missed change already
https://github.com/breez/breez-sdk/actions/runs/6676790656/job/18146199727#step:8:21

**Comment by dangeross** [comment]
This is great. A cool next step would be to test the RN generated code against built bindings so it could pickup issues like #565

**Comment by JssDWt** [comment]
> This is great. A cool next step would be to test the RN generated code against built bindings so it could pickup issues like #565

That would be great too indeed. We need a way to compile as little as possible to check the bindings.

**Review by roeierez — APPROVED** [review]
LGTM

**Review by dangeross — APPROVED** [review]

**Pull request merged**
