### PR TITLE
fix build on macos

### PR DESCRIPTION
**Pull request by roeierez**
(cherry picked from commit 9142b3c21973a4cecccb1b7d9b124daa6b1570a8)

### CODE REVIEW

**Comment by JssDWt** [comment]
@roeierez I wonder if this change brings back [this issue](https://github.com/breez/c-breez/issues/553) on macOS? Did you test that?

**Comment by JssDWt** [comment]
Here's an example how mozilla is doing it now
https://github.com/mozilla/application-services/blob/74b4b850d93c1ec7b305042fb6c3f44712767f3d/components/support/rc_crypto/nss/nss_build_common/src/lib.rs#L75-L105

**Comment by dangeross** [comment]
> @roeierez I wonder if this change brings back [this issue](https://github.com/breez/c-breez/issues/553) on macOS?

I'm getting the same error running c-breez on this branch `dlopen failed: cannot locate symbol "__extenddftf2"`
```
Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@aff7a9) but could not find or invoke the GeneratedPluginRegistrant.
Received exception while registering
   java.lang.reflect.InvocationTargetException
   	at java.lang.reflect.Method.invoke(Native Method)
   	at io.flutter.embedding.engine.plugins.util.GeneratedPluginRegister.registerGeneratedPlugins(GeneratedPluginRegister.java:80)
   	at io.flutter.embedding.android.FlutterActivity.configureFlutterEngine(FlutterActivity.java:1277)
   	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:213)
   	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:634)
   	at android.app.Activity.performCreate(Activity.java:8305)
   	at android.app.Activity.performCreate(Activity.java:8284)
   	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
   	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
   	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
   	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
   	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
   	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
   	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
   	at android.os.Handler.dispatchMessage(Handler.java:106)
   	at android.os.Looper.loopOnce(Looper.java:201)
   	at android.os.Looper.loop(Looper.java:288)
   	at android.app.ActivityThread.main(ActivityThread.java:7872)
   	at java.lang.reflect.Method.invoke(Native Method)
   	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
   	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
   Caused by: java.lang.UnsatisfiedLinkError: Unable to load library 'breez_sdk_bindings':
   dlopen failed: cannot locate symbol "__extenddftf2" referenced by "/data/app/~~kLBDvGRUAG2pR4pLdwVczA==/com.cBreez.client.debug-mg7EEdSP86r_D-bBk-2xCw==/base.apk!/lib/x86_64/libbreez_sdk_bindings.so"...
   dlopen failed: cannot locate symbol "__extenddftf2" referenced by "/data/app/~~kLBDvGRUAG2pR4pLdwVczA==/com.cBreez.client.debug-mg7EEdSP86r_D-bBk-2xCw==/base.apk!/lib/x86_64/libbreez_sdk_bindings.so"...
   dlopen failed: cannot locate symbol "__extenddftf2" referenced by "/data/app/~~kLBDvGRUAG2pR4pLdwVczA==/com.cBreez.client.debug-mg7EEdSP86r_D-bBk-2xCw==/base.apk!/lib/x86_64/libbreez_sdk_bindings.so"...
   Native library (android-x86-64/libbreez_sdk_bindings.so) not found in resource path (.)
   	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:325)
   	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:481)
   	at com.sun.jna.Library$Handler.<init>(Library.java:197)
   	at com.sun.jna.Native.load(Native.java:618)
   	at com.sun.jna.Native.load(Native.java:592)
   	at breez_sdk._UniFFILib$Companion$INSTANCE$2.invoke(breez_sdk.kt:8007)
   	at breez_sdk._UniFFILib$Companion$INSTANCE$2.invoke(breez_sdk.kt:273)
   	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
   	at breez_sdk._UniFFILib$Companion.getINSTANCE$breez_sdk_debug(breez_sdk.kt:273)
   	at breez_sdk.Breez_sdkKt.setLogStream(breez_sdk.kt:7942)
   	at com.breez.breez_sdk.SdkLogInitializer.initializeNodeLogStream(SdkLogInitializer.kt:13)
   	at com.breez.breez_sdk.BreezSDKPlugin.onAttachedToEngine(BreezSDKPlugin.kt:25)
   	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.add(FlutterEngineConnectionRegistry.java:147)
   	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:24)
   	... 21 more
   	Suppressed: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__extenddftf2" referenced by "/data/app/~~kLBDvGRUAG2pR4pLdwVczA==/com.cBreez.client.debug-mg7EEdSP86r_D-bBk-2xCw==/base.apk!/lib/x86_64/libbreez_sdk_bindings.so"...
   		at com.sun.jna.Native.open(Native Method)
   		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:213)
   		... 34 more
Suppressed: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__extenddftf2" referenced by "/data/app/~~kLBDvGRUAG2pR4pLdwVczA==/com.cBreez.client.debug-mg7EEdSP86r_D-bBk-2xCw==/base.apk!/lib/x86_64/libbreez_sdk_bindings.so"...
   		at com.sun.jna.Native.open(Native Method)
   		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:226)
   		... 34 more
   	Suppressed: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__extenddftf2" referenced by "/data/app/~~kLBDvGRUAG2pR4pLdwVczA==/com.cBreez.client.debug-mg7EEdSP86r_D-bBk-2xCw==/base.apk!/lib/x86_64/libbreez_sdk_bindings.so"...
   		at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
   		at java.lang.Runtime.loadLibrary0(Runtime.java:998)
   		at java.lang.System.loadLibrary(System.java:1661)
   		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:240)
   		... 34 more
   	Suppressed: java.io.IOException: Native library (android-x86-64/libbreez_sdk_bindings.so) not found in resource path (.)
   		at com.sun.jna.Native.extractFromResourcePath(Native.java:1141)
   		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:297)
   		... 34 more
```

**Comment by JssDWt** [comment]
I think the path is different on silicon mac, that's why it's not compiling there. For me it appears to be `toolchains/llvm/prebuilt/{build_os}-x86_64/lib/clang/{clang_version}/lib/linux/` (note, lib instead of lib64). And the `NDK_CLANG_VERSION` has to be set, because it's 18 rather than the default version 14.0.7. When I change this in `build.rs` the compilation does work (on mac M3). So we add an exception for Darwin arm64 to target the `lib` directory rather than the `lib64` directory??

**Comment by roeierez** [comment]
Closing this in favor of: https://github.com/breez/breez-sdk/pull/972

**Pull request closed without merging**
