### PR TITLE
Update Android build clang to 17

### PR DESCRIPTION
**Pull request by dangeross**
This PR updates the clang version used to build android libraries to 17

### CODE REVIEW

**Review by roeierez — APPROVED** [review]
LGTM

**Comment by JssDWt** [comment]
I don't have clang 17 on my machine, what do you have to do to install that clang version? Is this all simply tied to the NDK version? Should we force a fixed NDK version? Or do some kind of match statement based on the NDK version?

**Comment by dangeross** [comment]
@JssDWt the current default NDK version on macos-latest is 26.3.11579264, with the included version of clang being 17. I think it recently changed from 25.2.9519653 being the default.

https://github.com/actions/runner-images/blob/main/images/macos/macos-14-arm64-Readme.md#android

I'm not sure what the best approach is, but it needs to support building locally and in the CI

**Comment by JssDWt** [comment]
> I'm not sure what the best approach is, but it needs to support building locally and in the CI

I think it should be fine this way. If someone has a different clang version they can set the `NDK_CLANG_VERSION` environment variable during the build. Maybe let's change the panic error message on line 33 to `Path {linkpath} not exists. Try setting the NDK_CLANG_VERSION environment variable.`

**Comment by dangeross** [comment]
> Maybe let's change the panic error message on line 33 to `Path {linkpath} not exists. Try setting the NDK_CLANG_VERSION environment variable.`

@JssDWt done

**Review by JssDWt — APPROVED** [review]

**Pull request merged**
